DROP TABLE PassEnter CASCADE CONSTRAINTS;
DROP TABLE PassExit CASCADE CONSTRAINTS;

DROP TABLE RunsOn CASCADE CONSTRAINTS;
DROP TABLE RouteStop CASCADE CONSTRAINTS;
DROP TABLE Schedule CASCADE CONSTRAINTS;
DROP TABLE Gate CASCADE CONSTRAINTS;

DROP TABLE ZonePass CASCADE CONSTRAINTS;
DROP TABLE TimedPass CASCADE CONSTRAINTS;
DROP TABLE Passes CASCADE CONSTRAINTS;

DROP TABLE SubwayTrain CASCADE CONSTRAINTS;
DROP TABLE TransportStation CASCADE CONSTRAINTS;

DROP TABLE Route CASCADE CONSTRAINTS;
DROP TABLE Passenger CASCADE CONSTRAINTS;
DROP TABLE Zone CASCADE CONSTRAINTS;
DROP TABLE TrainModel CASCADE CONSTRAINTS;